// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Services.ProductAPI.DatabaseContext;

#nullable disable

namespace Restaurant.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            ImageUrl = "https://sarovarblob.blob.core.windows.net/restaurant/1.jpg",
                            ProductDescription = "Samosa Ho yarr",
                            ProductName = "Samosa",
                            ProductPrice = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            ImageUrl = "https://sarovarblob.blob.core.windows.net/restaurant/2.jpg",
                            ProductDescription = "Mittho Chicken Momo",
                            ProductName = "Chicken Momo",
                            ProductPrice = 53.990000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            ImageUrl = "https://sarovarblob.blob.core.windows.net/restaurant/3.jpg",
                            ProductDescription = "Yesko craving bhaira cha",
                            ProductName = "Cheese Cake",
                            ProductPrice = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            ImageUrl = "https://sarovarblob.blob.core.windows.net/restaurant/4.jpg",
                            ProductDescription = "4 Products are enough",
                            ProductName = "Chowmein",
                            ProductPrice = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
